[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cs514-nba-project"
version = "0.1.0"
description = "NBA player performance modeling with baseline ML and transformer pipelines"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Elijah Parr" }
]
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
